version: '2'
services:
  api:
    restart: on-failure
    build: ./
    ports:
      - '3000:3000'
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf 
      - ./nginx/error.log:/etc/nginx/error_log.log
      - /etc/letsencrypt/:/etc/letsencrypt/